# Site
repository: sproogen/resume-theme
favicon: favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juan Miguel Alferez
title: Software Developer
email: juanalferez8@gmail.com
website: https://github.com/0Z4ru/0Z4ru.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  0Z4ru
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 0z4ru_
linkedin_username: juan-miguel-alferez-lopez-7741a327a
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://github.com/0Z4ru/0Z4ru.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: yo2.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hey!, I'm Miguel, I've worked as a web developer, consultant, I'm currently an infrastructure intern, I also have experience in mobile applications.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/0Z4ru
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/0Z4ru
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started my path as a developer at <mark>Cakephp</mark> and from there I started to grow with basic web programming tools like <mark>HTML, PHP and Node.js</mark> ,until now I am still learning to develop mobile applications in <mark>Flutter</mark> in my spare time. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wbox
        link: http://bizbox.mx/
        # link_text: boringcompany.com
        sub_title: Web Developer
        caption: May 2022 - June 2023
        title: Almex
        link: https://www.almidones.com.mx/
        # link_text: boringcompany.com
        sub_title: infrastructure scholarship
        caption: June 2023 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Backend experience, I have developed several cruds, among the most popular: for a financial company (Element Five), for a therapeutic school (Floral Lake), a serious game-type desktop application for understanding ADHD, a video game for desktop as theme the superhero arrow, develop 2 web pages one type ecommerce drag and drop, and the other api type as theme the popular anime series pokemon, help maintain the pages: hoyfaturo.com and waydata.cloud

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad De Guadalajara
        caption: 2020 - Present
        sub_title: Computer Engineering
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I have learned a lot about the operation of a computer both internally and externally, I started practicing in the middle of my career, which made me grow even more in both personal and mental fields, in addition to that I always set out to help anyone in programming fields web, because from my point of view that makes them grow both to them and to me

          I spent a lot of my free time as a <mark>Gym Rat</mark> I hardly use the university gym, even though I love running on the university track

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in web development and software engineering some of my other interests and hobbies are:
      - Gym
      - Gaming
      - Programing Games 
      - Music


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
